[versions]
# libraries
junit = "4.13.2"

# plugins
kotlin = "2.0.20"
changelog = "2.2.1"
gradleIntelliJPlugin = "2.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
